# -*- coding: utf-8 -*-
"""06_Pytorch_Going Modular_Modular.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqLva_waTPkJd__abT1ZDbdZYPAgEQya
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Arnab-arp/Modular-Model-Training-Setup.git
# %cd Modular-Model-Training-Setup
!pip3 install -r requirements.txt
!ls

# Dowloading a dataset
import kagglehub

# Download latest version
path = kagglehub.dataset_download("balabaskar/cricket-legends-in-world-image-dataset")

print("Path to dataset files:", path)

!ls '/root/.cache/kagglehub/datasets/balabaskar/cricket-legends-in-world-image-dataset/versions/3/Cricket Legends/Cricket Legends'

!python3 train_model.py --help

!python3 train_model.py -m TinyVGG\
 -hu 224\
 -dp '/root/.cache/kagglehub/datasets/balabaskar/cricket-legends-in-world-image-dataset/versions/3/Cricket Legends/Cricket Legends'\
 -lr 0.001\
 -bs 32\
 -epc 50\
 -v True\
 -sa TestRun\
 -f .pt\
 -d cuda

!python3 train_model.py\
 -m Resnet50\
 -hu 224\
 -dp '/root/.cache/kagglehub/datasets/balabaskar/cricket-legends-in-world-image-dataset/versions/3/Cricket Legends/Cricket Legends'\
 -lr 0.001\
 -bs 32\
 -epc 50\
 -v True\
 -sa TestRun\
 -f .pt\
 -d cuda

